package com.example.demo.controller;

import java.util.LinkedList;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.example.demo.model.Cultivo;
import com.example.demo.model.Especie;
import com.example.demo.model.Plaga;
import com.example.demo.model.Producto;
import com.example.demo.model.Sustancia;
import com.example.demo.repository.CultivoRepository;
import com.example.demo.repository.EspecieRepository;
import com.example.demo.repository.PlagaRepository;
import com.example.demo.repository.ProductoRepository;
import com.example.demo.repository.SustanciaRepository;

@Controller
public class AppController {
	private LinkedList<Especie> listaespecies = new LinkedList<Especie>();
	private LinkedList<Especie> listaespecies2 = new LinkedList<Especie>();
	private LinkedList<Especie> listaespecies3 = new LinkedList<Especie>();
	private LinkedList<Especie> listaespecies4 = new LinkedList<Especie>();
	private LinkedList<Plaga> listaplagas = new LinkedList<Plaga>();
	private LinkedList<Plaga> listaplagas1 = new LinkedList<Plaga>();
	private LinkedList<Plaga> listaplagas2 = new LinkedList<Plaga>();
	private LinkedList<Plaga> listaplagas3 = new LinkedList<Plaga>();
	private LinkedList<Plaga> listaplagas4 = new LinkedList<Plaga>();
	private LinkedList<Plaga> listaplagas5 = new LinkedList<Plaga>();
	private LinkedList<Plaga> listaplagas6 = new LinkedList<Plaga>();
	private LinkedList<Plaga> listaplagas7 = new LinkedList<Plaga>();
	private LinkedList<Producto> listaproductos = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos1 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos2 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos3 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos4 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos5 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos6 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos7 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos8 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos9 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos10 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos11 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos12 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos13 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos14 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos15 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos16 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos17 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos18 = new LinkedList<Producto>();
	private LinkedList<Producto> listaproductos19 = new LinkedList<Producto>();
	private LinkedList<Sustancia> listasustancias = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias1 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias2 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias3 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias4 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias5 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias6 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias7 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias8 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias9 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias10 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias11 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias12 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias13 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias14 = new LinkedList<Sustancia>();
	private LinkedList<Sustancia> listasustancias15 = new LinkedList<Sustancia>();
	@Autowired
	private CultivoRepository repCultivos;
	@Autowired
	private EspecieRepository repEspecies;
	@Autowired
	private PlagaRepository repPlagas;
	@Autowired
	private ProductoRepository repProductos;
	@Autowired
	private SustanciaRepository repSustancias;
	
	@PostConstruct
	public void init() {

		Producto pr1 = new Producto("nombreProducto1","url1");
		Producto pr2 = new Producto("nombreProducto2","url2");
		Producto pr3 = new Producto("nombreProducto3","url3");
		Producto pr4 = new Producto("nombreProducto4","url4");
		Producto pr5 = new Producto("nombreProducto5","url5");
		Producto pr6 = new Producto("nombreProducto6","url6");
		Producto pr7 = new Producto("nombreProducto7","url7");
		Producto pr8 = new Producto("nombreProducto8","url8");
		Producto pr9 = new Producto("nombreProducto9","url9");
		Producto pr10 = new Producto("nombreProducto10","url10");
		Producto pr11 = new Producto("nombreProducto11","url11");
		Producto pr12 = new Producto("nombreProducto12","url12");
		Producto pr13 = new Producto("nombreProducto13","url13");
		Producto pr14 = new Producto("nombreProducto14","url14");
		Producto pr15 = new Producto("nombreProducto15","url15");
		Producto pr16 = new Producto("nombreProducto16","url16");
		Producto pr17 = new Producto("nombreProducto17","url17");
		Producto pr18 = new Producto("nombreProducto18","url18");
		Producto pr19 = new Producto("nombreProducto19","url19");
		Producto pr20 = new Producto("nombreProducto20","url20");
		Producto pr21 = new Producto("nombreProducto21","url21");
		Producto pr22 = new Producto("nombreProducto22","url22");
		Producto pr23 = new Producto("nombreProducto23","url23");
		Producto pr24 = new Producto("nombreProducto24","url24");
		Producto pr25 = new Producto("nombreProducto25","url25");
		Producto pr26 = new Producto("nombreProducto26","url26");
		Producto pr27 = new Producto("nombreProducto27","url27");
		Producto pr28 = new Producto("nombreProducto28","url28");
		Producto pr29 = new Producto("nombreProducto29","url29");
		Producto pr30 = new Producto("nombreProducto30","url30");
		repProductos.save(pr1);
		repProductos.save(pr2);
		repProductos.save(pr3);
		repProductos.save(pr4);
		repProductos.save(pr5);
		repProductos.save(pr6);
		repProductos.save(pr7);
		repProductos.save(pr8);
		repProductos.save(pr9);
		repProductos.save(pr10);
		repProductos.save(pr11);
		repProductos.save(pr12);
		repProductos.save(pr13);
		repProductos.save(pr14);
		repProductos.save(pr15);
		repProductos.save(pr16);
		repProductos.save(pr17);
		repProductos.save(pr18);
		repProductos.save(pr19);
		repProductos.save(pr20);
		repProductos.save(pr21);
		repProductos.save(pr22);
		repProductos.save(pr23);
		repProductos.save(pr24);
		repProductos.save(pr25);
		repProductos.save(pr26);
		repProductos.save(pr27);
		repProductos.save(pr28);
		repProductos.save(pr29);
		repProductos.save(pr30);
		
		Sustancia s1 = new Sustancia("nombreSustancia1",listaproductos);
		repSustancias.save(s1);
		s1.getProductos().add(pr1);
		s1.getProductos().add(pr2);
		s1.getProductos().add(pr3);
		s1.getProductos().add(pr4);
		s1.getProductos().add(pr5);
		repSustancias.save(s1);
		
		Sustancia s2 = new Sustancia("nombreSustancia2",listaproductos1);
		repSustancias.save(s2);
		s2.getProductos().add(pr1);
		s2.getProductos().add(pr2);
		s2.getProductos().add(pr3);
		s2.getProductos().add(pr4);
		s2.getProductos().add(pr5);
		repSustancias.save(s2);
		
		Sustancia s3 = new Sustancia("nombreSustancia3",listaproductos2);
		repSustancias.save(s3);
		s3.getProductos().add(pr6);
		s3.getProductos().add(pr7);
		repSustancias.save(s3);
		Sustancia s4 = new Sustancia("nombreSustancia4",listaproductos3);
		repSustancias.save(s4);
		s4.getProductos().add(pr8);
		s4.getProductos().add(pr9);
		repSustancias.save(s4);
		Sustancia s5 = new Sustancia("nombreSustancia5",listaproductos4);
		repSustancias.save(s5);
		s5.getProductos().add(pr10);
		s5.getProductos().add(pr11);
		repSustancias.save(s5);
		Sustancia s6 = new Sustancia("nombreSustancia6",listaproductos5);
		repSustancias.save(s6);
		s6.getProductos().add(pr12);
		repSustancias.save(s6);
		Sustancia s7 = new Sustancia("nombreSustancia7",listaproductos6);
		repSustancias.save(s7);
		s7.getProductos().add(pr13);
		repSustancias.save(s7);
		Sustancia s8 = new Sustancia("nombreSustancia8",listaproductos7);
		repSustancias.save(s8);
		s8.getProductos().add(pr14);
		repSustancias.save(s8);
		Sustancia s9 = new Sustancia("nombreSustancia9",listaproductos8);
		repSustancias.save(s9);
		s9.getProductos().add(pr15);
		repSustancias.save(s9);
		Sustancia s10 = new Sustancia("nombreSustancia10",listaproductos9);
		repSustancias.save(s10);
		s10.getProductos().add(pr16);
		s10.getProductos().add(pr17);
		repSustancias.save(s10);
		Sustancia s11 = new Sustancia("nombreSustancia11",listaproductos10);
		repSustancias.save(s11);
		s11.getProductos().add(pr18);
		s11.getProductos().add(pr19);
		s11.getProductos().add(pr20);
		repSustancias.save(s11);
		Sustancia s12 = new Sustancia("nombreSustancia12",listaproductos11);
		repSustancias.save(s12);
		s12.getProductos().add(pr21);
		repSustancias.save(s12);
		Sustancia s13 = new Sustancia("nombreSustancia13",listaproductos12);
		repSustancias.save(s13);
		s13.getProductos().add(pr22);
		s13.getProductos().add(pr23);
		repSustancias.save(s13);
		Sustancia s14 = new Sustancia("nombreSustancia14",listaproductos13);
		repSustancias.save(s14);
		s14.getProductos().add(pr24);
		repSustancias.save(s14);
		Sustancia s15 = new Sustancia("nombreSustancia15",listaproductos14);
		repSustancias.save(s15);
		s15.getProductos().add(pr25);
		repSustancias.save(s15);
		Sustancia s16 = new Sustancia("nombreSustancia16",listaproductos15);
		repSustancias.save(s16);
		s16.getProductos().add(pr26);
		repSustancias.save(s16);
		Sustancia s17 = new Sustancia("nombreSustancia17",listaproductos16);
		repSustancias.save(s17);
		s17.getProductos().add(pr27);
		repSustancias.save(s17);
		Sustancia s18 = new Sustancia("nombreSustancia18",listaproductos17);
		repSustancias.save(s18);
		s18.getProductos().add(pr28);
		repSustancias.save(s18);
		Sustancia s19 = new Sustancia("nombreSustancia19",listaproductos18);
		repSustancias.save(s19);
		s19.getProductos().add(pr29);
		repSustancias.save(s19);
		Sustancia s20 = new Sustancia("nombreSustancia20",listaproductos19);
		repSustancias.save(s20);
		s20.getProductos().add(pr30);
		repSustancias.save(s20);
		
		Plaga p1 = new Plaga("nombreVPlaga1","nombreCPlaga1","urlPlaga1",listasustancias);
		repPlagas.save(p1);
		p1.getSustancias().add(s1);
		p1.getSustancias().add(s2);
		p1.getSustancias().add(s3);
		repPlagas.save(p1);
		Plaga p2 = new Plaga("nombreVPlaga2","nombreCPlaga2","urlPlaga2",listasustancias1);
		repPlagas.save(p2);
		p2.getSustancias().add(s1);
		p2.getSustancias().add(s2);
		p2.getSustancias().add(s4);
		p2.getSustancias().add(s5);
		p2.getSustancias().add(s6);
		p2.getSustancias().add(s7);
		repPlagas.save(p2);
		Plaga p3 = new Plaga("nombreVPlaga3","nombreCPlaga3","urlPlaga3",listasustancias2);
		repPlagas.save(p3);
		p3.getSustancias().add(s1);
		p3.getSustancias().add(s2);
		p3.getSustancias().add(s4);
		p3.getSustancias().add(s5);
		p3.getSustancias().add(s6);
		p3.getSustancias().add(s7);
		repPlagas.save(p3);
		Plaga p4 = new Plaga("nombreVPlaga4","nombreCPlaga4","urlPlaga4",listasustancias3);
		repPlagas.save(p4);
		p4.getSustancias().add(s8);
		repPlagas.save(p4);
		Plaga p5 = new Plaga("nombreVPlaga5","nombreCPlaga5","urlPlaga5",listasustancias4);
		repPlagas.save(p5);
		p5.getSustancias().add(s9);
		repPlagas.save(p5);
		Plaga p6 = new Plaga("nombreVPlaga6","nombreCPlaga6","urlPlaga6",listasustancias5);
		repPlagas.save(p6);
		p6.getSustancias().add(s10);
		repPlagas.save(p6);
		Plaga p7 = new Plaga("nombreVPlaga7","nombreCPlaga7","urlPlaga7",listasustancias6);
		repPlagas.save(p7);
		p7.getSustancias().add(s11);
		repPlagas.save(p7);
		Plaga p8 = new Plaga("nombreVPlaga8","nombreCPlaga8","urlPlaga8",listasustancias7);
		repPlagas.save(p8);
		p8.getSustancias().add(s12);
		repPlagas.save(p8);
		Plaga p9 = new Plaga("nombreVPlaga9","nombreCPlaga9","urlPlaga9",listasustancias8);
		repPlagas.save(p9);
		p9.getSustancias().add(s13);
		repPlagas.save(p9);
		Plaga p10 = new Plaga("nombreVPlaga10","nombreCPlaga10","urlPlaga10",listasustancias9);
		repPlagas.save(p10);
		p10.getSustancias().add(s14);
		repPlagas.save(p10);
		Plaga p11 = new Plaga("nombreVPlaga11","nombreCPlaga11","urlPlaga11",listasustancias10);
		repPlagas.save(p11);
		p11.getSustancias().add(s15);
		repPlagas.save(p11);
		Plaga p12 = new Plaga("nombreVPlaga12","nombreCPlaga12","urlPlaga12",listasustancias11);
		repPlagas.save(p12);
		p12.getSustancias().add(s16);
		repPlagas.save(p12);
		Plaga p13 = new Plaga("nombreVPlaga13","nombreCPlaga13","urlPlaga13",listasustancias12);
		repPlagas.save(p13);
		p13.getSustancias().add(s17);
		repPlagas.save(p13);
		Plaga p14 = new Plaga("nombreVPlaga14","nombreCPlaga14","urlPlaga14",listasustancias13);
		repPlagas.save(p14);
		p14.getSustancias().add(s18);
		repPlagas.save(p14);
		Plaga p15 = new Plaga("nombreVPlaga15","nombreCPlaga15","urlPlaga15",listasustancias14);
		repPlagas.save(p15);
		p15.getSustancias().add(s19);
		repPlagas.save(p15);
		Plaga p16 = new Plaga("nombreVPlaga16","nombreCPlaga16","urlPlaga16",listasustancias15);
		repPlagas.save(p16);
		p16.getSustancias().add(s20);
		repPlagas.save(p16);
		
		Especie e1 = new Especie("nombreVulgarEspecie1","nombreCientificoEspecie1",listaplagas);
		repEspecies.save(e1);
		e1.getPlagas().add(p1);
		e1.getPlagas().add(p2);
		repEspecies.save(e1);
		Especie e2 = new Especie("nombreVulgarEspecie2","nombreCientificoEspecie2",listaplagas1);
		repEspecies.save(e2);
		e2.getPlagas().add(p1);
		e2.getPlagas().add(p3);
		e2.getPlagas().add(p4);
		repEspecies.save(e2);
		Especie e3 = new Especie("nombreVulgarEspecie3","nombreCientificoEspecie3",listaplagas2);
		repEspecies.save(e3);
		e3.getPlagas().add(p1);
		e3.getPlagas().add(p3);
		e3.getPlagas().add(p5);
		e3.getPlagas().add(p6);
		repEspecies.save(e3);
		Especie e4 = new Especie("nombreVulgarEspecie4","nombreCientificoEspecie4",listaplagas3);
		repEspecies.save(e4);
		e4.getPlagas().add(p7);
		e4.getPlagas().add(p8);
		repEspecies.save(e4);
		Especie e5 = new Especie("nombreVulgarEspecie5","nombreCientificoEspecie5",listaplagas4);
		repEspecies.save(e5);
		e5.getPlagas().add(p9);
		e5.getPlagas().add(p10);
		repEspecies.save(e5);
		Especie e6 = new Especie("nombreVulgarEspecie6","nombreCientificoEspecie6",listaplagas5);
		repEspecies.save(e6);
		e6.getPlagas().add(p11);
		e6.getPlagas().add(p12);
		repEspecies.save(e6);
		Especie e7 = new Especie("nombreVulgarEspecie7","nombreCientificoEspecie7",listaplagas6);
		repEspecies.save(e7);
		e7.getPlagas().add(p13);
		e7.getPlagas().add(p14);
		repEspecies.save(e7);
		Especie e8 = new Especie("nombreVulgarEspecie8","nombreCientificoEspecie8",listaplagas7);
		repEspecies.save(e8);
		e8.getPlagas().add(p15);
		e8.getPlagas().add(p16);
		repEspecies.save(e8);

		Cultivo c1 = new Cultivo("Cultivo 1",listaespecies);
		repCultivos.save(c1);
		c1.getEspecies().add(e1);
		c1.getEspecies().add(e2);
		c1.getEspecies().add(e3);
		c1.getEspecies().add(e4);
		repCultivos.save(c1);
		Cultivo c2 = new Cultivo("Cultivo 2",listaespecies2);
		repCultivos.save(c2);
		c1.getEspecies().add(e1);
		c1.getEspecies().add(e2);
		c1.getEspecies().add(e8);
		repCultivos.save(c2);
		Cultivo c3 = new Cultivo("Cultivo 3",listaespecies3);
		repCultivos.save(c3);
		c1.getEspecies().add(e5);
		c1.getEspecies().add(e6);
		c1.getEspecies().add(e7);
		repCultivos.save(c3);
		Cultivo c4 = new Cultivo("Cultivo 4",listaespecies4);
		repCultivos.save(c4);
		c1.getEspecies().add(e8);
		repCultivos.save(c4);
	}

}
