package com.example.demo.controller;

import java.util.LinkedList;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.example.demo.model.Cultivo;
import com.example.demo.model.Especie;
import com.example.demo.model.Plaga;
import com.example.demo.model.Producto;
import com.example.demo.model.Sustancia;
import com.example.demo.repository.CultivoRepository;
import com.example.demo.repository.EspecieRepository;
import com.example.demo.repository.PlagaRepository;
import com.example.demo.repository.ProductoRepository;
import com.example.demo.repository.SustanciaRepository;

@Controller
public class AppController {
	private LinkedList<Cultivo> listacultivos = new LinkedList<Cultivo>();
	private LinkedList<Especie> listaespecies = new LinkedList<Especie>();
	private LinkedList<Especie> listaespecies2 = new LinkedList<Especie>();
	private LinkedList<Especie> listaespecies3 = new LinkedList<Especie>();
	private LinkedList<Especie> listaespecies4 = new LinkedList<Especie>();
	private LinkedList<Plaga> listaplagas = new LinkedList<Plaga>();
	private LinkedList<Producto> listaproductos = new LinkedList<Producto>();
	private LinkedList<Sustancia> listasustancias = new LinkedList<Sustancia>();
	@Autowired
	private CultivoRepository repCultivos;
	@Autowired
	private EspecieRepository repEspecies;
	@Autowired
	private PlagaRepository repPlagas;
	@Autowired
	private ProductoRepository repProductos;
	@Autowired
	private SustanciaRepository repSustancias;
	
	@PostConstruct
	public void init() {

		Producto pr1 = new Producto("nombreProducto1","url1");
		Producto pr2 = new Producto("nombreProducto2","url2");
		Producto pr3 = new Producto("nombreProducto3","url3");
		Producto pr4 = new Producto("nombreProducto4","url4");
		Producto pr5 = new Producto("nombreProducto5","url5");
		Producto pr6 = new Producto("nombreProducto6","url6");
		Producto pr7 = new Producto("nombreProducto7","url7");
		Producto pr8 = new Producto("nombreProducto8","url8");
		Producto pr9 = new Producto("nombreProducto9","url9");
		Producto pr10 = new Producto("nombreProducto10","url10");
		Producto pr11 = new Producto("nombreProducto11","url11");
		Producto pr12 = new Producto("nombreProducto12","url12");
		Producto pr13 = new Producto("nombreProducto13","url13");
		Producto pr14 = new Producto("nombreProducto14","url14");
		Producto pr15 = new Producto("nombreProducto15","url15");
		Producto pr16 = new Producto("nombreProducto16","url16");
		Producto pr17 = new Producto("nombreProducto17","url17");
		Producto pr18 = new Producto("nombreProducto18","url18");
		Producto pr19 = new Producto("nombreProducto19","url19");
		Producto pr20 = new Producto("nombreProducto20","url20");
		Producto pr21 = new Producto("nombreProducto21","url21");
		Producto pr22 = new Producto("nombreProducto22","url22");
		Producto pr23 = new Producto("nombreProducto23","url23");
		Producto pr24 = new Producto("nombreProducto24","url24");
		Producto pr25 = new Producto("nombreProducto25","url25");
		Producto pr26 = new Producto("nombreProducto26","url26");
		Producto pr27 = new Producto("nombreProducto27","url27");
		Producto pr28 = new Producto("nombreProducto28","url28");
		Producto pr29 = new Producto("nombreProducto29","url29");
		Producto pr30 = new Producto("nombreProducto30","url30");
		repProductos.save(pr1);
		repProductos.save(pr2);
		repProductos.save(pr3);
		repProductos.save(pr4);
		repProductos.save(pr5);
		repProductos.save(pr6);
		repProductos.save(pr7);
		repProductos.save(pr8);
		repProductos.save(pr9);
		repProductos.save(pr10);
		repProductos.save(pr11);
		repProductos.save(pr12);
		repProductos.save(pr13);
		repProductos.save(pr14);
		repProductos.save(pr15);
		repProductos.save(pr16);
		repProductos.save(pr17);
		repProductos.save(pr18);
		repProductos.save(pr19);
		repProductos.save(pr20);
		repProductos.save(pr21);
		repProductos.save(pr22);
		repProductos.save(pr23);
		repProductos.save(pr24);
		repProductos.save(pr25);
		repProductos.save(pr26);
		repProductos.save(pr27);
		repProductos.save(pr28);
		repProductos.save(pr29);
		repProductos.save(pr30);
		
		
		Sustancia s1 = new Sustancia("nombreSustancia1",listaproductos);
		s1.getProductos().add(pr1);
		s1.getProductos().add(pr2);
		s1.getProductos().add(pr3);
		s1.getProductos().add(pr4);
		s1.getProductos().add(pr5);
		Sustancia s2 = new Sustancia("nombreSustancia2",listaproductos);
		s2.getProductos().add(pr1);
		s2.getProductos().add(pr2);
		s2.getProductos().add(pr3);
		s2.getProductos().add(pr4);
		s2.getProductos().add(pr5);
		Sustancia s3 = new Sustancia("nombreSustancia3",listaproductos);
		s3.getProductos().add(pr6);
		s3.getProductos().add(pr7);
		Sustancia s4 = new Sustancia("nombreSustancia4",listaproductos);
		s4.getProductos().add(pr8);
		s4.getProductos().add(pr9);
		Sustancia s5 = new Sustancia("nombreSustancia5",listaproductos);
		s5.getProductos().add(pr10);
		s5.getProductos().add(pr11);
		Sustancia s6 = new Sustancia("nombreSustancia6",listaproductos);
		s6.getProductos().add(pr12);
		Sustancia s7 = new Sustancia("nombreSustancia7",listaproductos);
		s7.getProductos().add(pr13);
		Sustancia s8 = new Sustancia("nombreSustancia8",listaproductos);
		s8.getProductos().add(pr14);
		Sustancia s9 = new Sustancia("nombreSustancia9",listaproductos);
		s9.getProductos().add(pr15);
		Sustancia s10 = new Sustancia("nombreSustancia10",listaproductos);
		s10.getProductos().add(pr16);
		s10.getProductos().add(pr17);
		Sustancia s11 = new Sustancia("nombreSustancia11",listaproductos);
		s11.getProductos().add(pr18);
		s11.getProductos().add(pr19);
		s11.getProductos().add(pr20);
		Sustancia s12 = new Sustancia("nombreSustancia12",listaproductos);
		s12.getProductos().add(pr21);
		Sustancia s13 = new Sustancia("nombreSustancia13",listaproductos);
		s13.getProductos().add(pr22);
		s13.getProductos().add(pr23);
		Sustancia s14 = new Sustancia("nombreSustancia14",listaproductos);
		s14.getProductos().add(pr24);
		Sustancia s15 = new Sustancia("nombreSustancia15",listaproductos);
		s15.getProductos().add(pr25);
		Sustancia s16 = new Sustancia("nombreSustancia16",listaproductos);
		s16.getProductos().add(pr26);
		Sustancia s17 = new Sustancia("nombreSustancia17",listaproductos);
		s17.getProductos().add(pr27);
		Sustancia s18 = new Sustancia("nombreSustancia18",listaproductos);
		s18.getProductos().add(pr28);
		Sustancia s19 = new Sustancia("nombreSustancia19",listaproductos);
		s19.getProductos().add(pr29);
		Sustancia s20 = new Sustancia("nombreSustancia20",listaproductos);
		s20.getProductos().add(pr30);
		repSustancias.save(s1);
		repSustancias.save(s2);
		repSustancias.save(s3);
		repSustancias.save(s4);
		repSustancias.save(s5);
		repSustancias.save(s6);
		repSustancias.save(s7);
		repSustancias.save(s8);
		repSustancias.save(s9);
		repSustancias.save(s10);
		repSustancias.save(s11);
		repSustancias.save(s12);
		repSustancias.save(s13);
		repSustancias.save(s14);
		repSustancias.save(s15);
		repSustancias.save(s16);
		repSustancias.save(s17);
		repSustancias.save(s18);
		repSustancias.save(s19);
		repSustancias.save(s20);

		Plaga p1 = new Plaga("nombreVPlaga1","nombreCPlaga1","urlPlaga1",listasustancias);
		p1.getSustancias().add(s1);
		p1.getSustancias().add(s2);
		p1.getSustancias().add(s3);
		Plaga p2 = new Plaga("nombreVPlaga2","nombreCPlaga2","urlPlaga2",listasustancias);
		p2.getSustancias().add(s1);
		p2.getSustancias().add(s2);
		p2.getSustancias().add(s4);
		p2.getSustancias().add(s5);
		p2.getSustancias().add(s6);
		p2.getSustancias().add(s7);
		Plaga p3 = new Plaga("nombreVPlaga3","nombreCPlaga3","urlPlaga3",listasustancias);
		p3.getSustancias().add(s1);
		p3.getSustancias().add(s2);
		p3.getSustancias().add(s4);
		p3.getSustancias().add(s5);
		p3.getSustancias().add(s6);
		p3.getSustancias().add(s7);
		Plaga p4 = new Plaga("nombreVPlaga4","nombreCPlaga4","urlPlaga4",listasustancias);
		p4.getSustancias().add(s8);
		Plaga p5 = new Plaga("nombreVPlaga5","nombreCPlaga5","urlPlaga5",listasustancias);
		p5.getSustancias().add(s9);
		Plaga p6 = new Plaga("nombreVPlaga6","nombreCPlaga6","urlPlaga6",listasustancias);
		p6.getSustancias().add(s10);
		Plaga p7 = new Plaga("nombreVPlaga7","nombreCPlaga7","urlPlaga7",listasustancias);
		p7.getSustancias().add(s11);
		Plaga p8 = new Plaga("nombreVPlaga8","nombreCPlaga8","urlPlaga8",listasustancias);
		p8.getSustancias().add(s12);
		Plaga p9 = new Plaga("nombreVPlaga9","nombreCPlaga9","urlPlaga9",listasustancias);
		p9.getSustancias().add(s13);
		Plaga p10 = new Plaga("nombreVPlaga10","nombreCPlaga10","urlPlaga10",listasustancias);
		p10.getSustancias().add(s14);
		Plaga p11 = new Plaga("nombreVPlaga11","nombreCPlaga11","urlPlaga11",listasustancias);
		p11.getSustancias().add(s15);
		Plaga p12 = new Plaga("nombreVPlaga12","nombreCPlaga12","urlPlaga12",listasustancias);
		p12.getSustancias().add(s16);
		Plaga p13 = new Plaga("nombreVPlaga13","nombreCPlaga13","urlPlaga13",listasustancias);
		p13.getSustancias().add(s17);
		Plaga p14 = new Plaga("nombreVPlaga14","nombreCPlaga14","urlPlaga14",listasustancias);
		p14.getSustancias().add(s18);
		Plaga p15 = new Plaga("nombreVPlaga15","nombreCPlaga15","urlPlaga15",listasustancias);
		p15.getSustancias().add(s19);
		Plaga p16 = new Plaga("nombreVPlaga16","nombreCPlaga16","urlPlaga16",listasustancias);
		p16.getSustancias().add(s20);
		repPlagas.save(p1);
		repPlagas.save(p2);
		repPlagas.save(p3);
		repPlagas.save(p4);
		repPlagas.save(p5);
		repPlagas.save(p6);
		repPlagas.save(p7);
		repPlagas.save(p8);
		repPlagas.save(p9);
		repPlagas.save(p10);
		repPlagas.save(p11);
		repPlagas.save(p12);
		repPlagas.save(p13);
		repPlagas.save(p14);
		repPlagas.save(p15);
		repPlagas.save(p16);
		
		Especie e1 = new Especie("nombreVulgarEspecie1","nombreCientificoEspecie1",listaplagas);
		e1.getPlagas().add(p1);
		e1.getPlagas().add(p2);
		Especie e2 = new Especie("nombreVulgarEspecie2","nombreCientificoEspecie2",listaplagas);
		e2.getPlagas().add(p1);
		e2.getPlagas().add(p3);
		e2.getPlagas().add(p4);
		Especie e3 = new Especie("nombreVulgarEspecie3","nombreCientificoEspecie3",listaplagas);
		e3.getPlagas().add(p1);
		e3.getPlagas().add(p3);
		e3.getPlagas().add(p5);
		e3.getPlagas().add(p6);
		Especie e4 = new Especie("nombreVulgarEspecie4","nombreCientificoEspecie4",listaplagas);
		e4.getPlagas().add(p7);
		e4.getPlagas().add(p8);
		Especie e5 = new Especie("nombreVulgarEspecie5","nombreCientificoEspecie5",listaplagas);
		e5.getPlagas().add(p9);
		e5.getPlagas().add(p10);
		Especie e6 = new Especie("nombreVulgarEspecie6","nombreCientificoEspecie6",listaplagas);
		e6.getPlagas().add(p11);
		e6.getPlagas().add(p12);
		Especie e7 = new Especie("nombreVulgarEspecie7","nombreCientificoEspecie7",listaplagas);
		e7.getPlagas().add(p13);
		e7.getPlagas().add(p14);
		Especie e8 = new Especie("nombreVulgarEspecie8","nombreCientificoEspecie8",listaplagas);
		e8.getPlagas().add(p15);
		e9.getPlagas().add(p16);
		repEspecies.save(e1);
		repEspecies.save(e2);
		repEspecies.save(e3);
		repEspecies.save(e4);
		repEspecies.save(e5);
		repEspecies.save(e6);
		repEspecies.save(e7);
		repEspecies.save(e8);
		
		listaespecies.add(e1);
		listaespecies.add(e2);
		listaespecies.add(e3);
		listaespecies.add(e4);
		listaespecies2.add(e1);
		listaespecies2.add(e2);
		listaespecies2.add(e8);
		listaespecies3.add(e5);
		listaespecies3.add(e6);
		listaespecies3.add(e7);
		listaespecies4.add(e8);
		Cultivo c1 = new Cultivo("Cultivo 1",listaespecies);
		Cultivo c2 = new Cultivo("Cultivo 2",listaespecies2);
		Cultivo c3 = new Cultivo("Cultivo 3",listaespecies3);
		Cultivo c4 = new Cultivo("Cultivo 4",listaespecies4);
		repCultivos.save(c1);
		repCultivos.save(c2);
		repCultivos.save(c3);
		repCultivos.save(c4);
	}

}
